### ISSUE TITLE
Please support python3+

### ISSUE THREAD

**Issue by 007bsd** [kowalpy/Robot-Framework-FTP-Library#10]
When trying to install csvlibrary with python3 getting below error. It seems it is yet support python3.

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/fr/jtjjqpbs1sx0lxh6qbgzgdjw00gftq/T/pip-build-nyn_ua1n/robotframework-ftplibrary/

Kindly provide the support for python3 as well

**Comment by kowalpy** [comment]
I don't understand which library you mean. I have never contributed to robotframework-csvlibrary. robotframework-ftplibrary is not depending on robotframework-csvlibrary.

**Comment by 007bsd** [comment]
Sorry. I meant ftp library only. The same error I was getting for CSV as well. :-(

**Comment by DirkRichter** [comment]
robotframework-ftplibrary has python3 support since merge of https://github.com/kowalpy/Robot-Framework-FTP-Library/pull/8

Just a new release is missing, but you can take the code from git.

**Comment by kowalpy** [comment]
Ok ok, I am aware of a need to make new release. I'll trigger it soon.

@DirkRichter if the error found by @007bsd is the one you fixed in https://github.com/kowalpy/Robot-Framework-FTP-Library/pull/8 then error message sucks

**Comment by kowalpy** [comment]
1.5 released
