### ISSUE TITLE
Running commands being on remote server

### ISSUE THREAD

**Issue by petr0ff** [kowalpy/Robot-Framework-FTP-Library#2]
Hi! First of all, great thanks for your library, it's very useful. 

I have an issue/feature request: is it possible to run FtpLibrary keywords being logged in to the remote server? Like I use SSHLibrary to ssh on remote server and then use FtpLibrary commands from there.

Thanks!

**Comment by kowalpy** [comment]
Sure, it is possible with use of robotframework remote library but it requires implementation. I will create that but I am not sure how soon.

**Comment by kowalpy** [comment]
Blocked by https://github.com/kowalpy/Robot-Framework-FTP-Library/issues/3

**Comment by kowalpy** [comment]
Blocking point removed

**Comment by kowalpy** [comment]
Done. 

@petr0ff please test before I upload release 1.4 to pipy server.

**Comment by petr0ff** [comment]
Great thanks! Sorry, had no chance to test it, hope to check it on the next week :(

**Comment by kowalpy** [comment]
No worries. I'll wait :-)

**Comment by kowalpy** [comment]
1.4 has been released. Please close this ticket

**Comment by petr0ff** [comment]
It was fine, great thanks again
