### ISSUE TITLE
ftp always switch to pasv mode for file transfer

### ISSUE THREAD

**Issue by elschman** [kowalpy/Robot-Framework-FTP-Library#20]
In case of server behind a firewall it would be good to have the option to switch on the active mode for filetransfer. best wishes from siemensallee 1

**Comment by kowalpy** [comment]
Fixed by @scathaig. Please check version 1.9 and close the issue if it's ok. Greetings to Simensallee team :-)

**Comment by kowalpy** [comment]
Fixed in 1.9
