### ISSUE TITLE
'IOError: [Errno 32] The process cannot access the file'

### ISSUE THREAD

**Issue by jpeltonen** [kowalpy/Robot-Framework-FTP-Library#4]
Getting error after 'Download File' keyword trying to open file. Downloaded file appears only after IronPython process have terminated.

Using Robot Framework 3.0 (IronPython 2.7.6 on cli)

In FtpLibrary.py:

```
localFile = open(localPath, 'wb')
outputMsg += thisConn.retrbinary("RETR " + remoteFileName, localFile.write)
```

Should be changed to:

```
with open(localPath, 'wb') as localFile:
    outputMsg += thisConn.retrbinary("RETR " + remoteFileName, localFile.write)
```

**Comment by kowalpy** [comment]
I'll relelase 1.4 to pypi soon

**Comment by jpeltonen** [comment]
Ok. Thanks.

**Comment by kowalpy** [comment]
1.4 has been released.

**Comment by kowalpy** [comment]
Issue fixed. Please close the ticket.
